#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Facility Location Problem (P-Median)
Generated by ORMDSL-Gurobi

Problem:
    Given a set of customers and potential facility locations,
    select P facilities to minimize total weighted distance.
    
    Minimize sum(d[i][j] * x[i][j])
    Subject to:
        sum(y[j] for j in locations) = P
        sum(x[i][j] for j in locations) = 1 for all i
        x[i][j] <= y[j] for all i, j

Usage:
    python facility_location_example.py
"""

import gurobipy as gp
from gurobipy import GRB

def solve_facility_location():
    """Solve the P-Median Facility Location Problem."""
    
    # ===== Problem Data =====
    customers = ['c1', 'c2', 'c3', 'c4', 'c5']
    locations = ['l1', 'l2', 'l3', 'l4']
    P = 2  # Number of facilities to open
    
    # Customer demands/weights
    demand = {'c1': 10, 'c2': 15, 'c3': 8, 'c4': 12, 'c5': 5}
    
    # Distance matrix
    distance = {
        ('c1', 'l1'): 10, ('c1', 'l2'): 15, ('c1', 'l3'): 20, ('c1', 'l4'): 25,
        ('c2', 'l1'): 15, ('c2', 'l2'): 10, ('c2', 'l3'): 18, ('c2', 'l4'): 22,
        ('c3', 'l1'): 20, ('c3', 'l2'): 18, ('c3', 'l3'): 8,  ('c3', 'l4'): 16,
        ('c4', 'l1'): 25, ('c4', 'l2'): 22, ('c4', 'l3'): 16, ('c4', 'l4'): 10,
        ('c5', 'l1'): 18, ('c5', 'l2'): 14, ('c5', 'l3'): 12, ('c5', 'l4'): 15,
    }
    
    # ===== Create Model =====
    model = gp.Model('facility_location')
    
    # ===== Decision Variables =====
    # y[j] = 1 if facility j is opened, 0 otherwise
    y = model.addVars(locations, vtype=GRB.BINARY, name='y')
    
    # x[i][j] = 1 if customer i is assigned to facility j
    x = model.addVars(customers, locations, vtype=GRB.BINARY, name='x')
    
    # ===== Objective Function =====
    # Minimize total weighted distance
    model.setObjective(
        gp.quicksum(distance[i, j] * demand[i] * x[i, j] 
                   for i in customers for j in locations),
        GRB.MINIMIZE
    )
    
    # ===== Constraints =====
    # 1. Open exactly P facilities
    model.addConstr(
        gp.quicksum(y[j] for j in locations) == P,
        name='num_facilities'
    )
    
    # 2. Each customer must be assigned to exactly one facility
    for i in customers:
        model.addConstr(
            gp.quicksum(x[i, j] for j in locations) == 1,
            name=f'assign_{i}'
        )
    
    # 3. Customer can only be assigned to opened facilities
    for i in customers:
        for j in locations:
            model.addConstr(x[i, j] <= y[j], name=f'link_{i}_{j}')
    
    # ===== Solve =====
    model.optimize()
    
    # ===== Output =====
    print("=" * 60)
    print("Facility Location Problem (P-Median) - Results")
    print("=" * 60)
    
    if model.status == GRB.OPTIMAL:
        print(f"\nOptimal Total Cost: {model.objVal}")
        print(f"Solution Time: {model.runtime:.4f} seconds")
        
        print("\nOpened Facilities:")
        for j in locations:
            if y[j].x > 0.5:
                print(f"  {j}")
        
        print("\nCustomer Assignments:")
        for i in customers:
            for j in locations:
                if x[i, j].x > 0.5:
                    print(f"  {i} -> {j} (distance: {distance[i, j]})")
    else:
        print(f"Optimization failed with status: {model.status}")
    
    return model

if __name__ == '__main__':
    solve_facility_location()
