#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
0-1 Knapsack Problem Example
Generated by ORMDSL-Gurobi

Problem:
    Maximize sum(profit[i] * x[i])
    Subject to: sum(weight[i] * x[i]) <= capacity
               x[i] in {0, 1} for all i

Usage:
    python knapsack_example.py
"""

import gurobipy as gp
from gurobipy import GRB

def solve_knapsack():
    """Solve the 0-1 Knapsack Problem."""
    
    # ===== Problem Data =====
    items = ['item1', 'item2', 'item3', 'item4', 'item5']
    profits = {'item1': 10, 'item2': 20, 'item3': 15, 'item4': 25, 'item5': 30}
    weights = {'item1': 2, 'item2': 4, 'item3': 3, 'item4': 5, 'item5': 6}
    capacity = 10
    
    # ===== Create Model =====
    model = gp.Model('knapsack')
    
    # ===== Decision Variables =====
    # x[i] = 1 if item i is selected, 0 otherwise
    x = model.addVars(items, vtype=GRB.BINARY, name='x')
    
    # ===== Objective Function =====
    # Maximize total profit
    model.setObjective(
        gp.quicksum(profits[i] * x[i] for i in items),
        GRB.MAXIMIZE
    )
    
    # ===== Constraints =====
    # Weight capacity constraint
    model.addConstr(
        gp.quicksum(weights[i] * x[i] for i in items) <= capacity,
        name='weight_capacity'
    )
    
    # ===== Solve =====
    model.optimize()
    
    # ===== Output =====
    print("=" * 50)
    print("0-1 Knapsack Problem - Results")
    print("=" * 50)
    
    if model.status == GRB.OPTIMAL:
        print(f"\nOptimal Profit: {model.objVal}")
        print(f"Solution Time: {model.runtime:.4f} seconds")
        print("\nSelected Items:")
        for i in items:
            if x[i].x > 0.5:
                print(f"  {i}: profit={profits[i]}, weight={weights[i]}")
        
        total_weight = sum(weights[i] * x[i].x for i in items)
        print(f"\nTotal Weight: {total_weight} / {capacity}")
    else:
        print(f"Optimization failed with status: {model.status}")
    
    return model

if __name__ == '__main__':
    solve_knapsack()
