package ormgurobi

/**
 * AST到Gurobi代码生成器
 * 将ORMDSL的抽象语法树转换为Gurobi Python API调用
 */

import dsl.ormdsl_._

object AST2Gurobi {
  
  /**
   * 操作符转换
   */
  def printGurobi(x: Aop): String = x match {
    case Plus => "+"
    case Minus => "-"
    case Times => "*"
    case Div => "/"
  }
  
  def printGurobi(x: Cop): String = x match {
    case Less => "<"
    case Greater => ">"
    case LessEq => "<="
    case GreaterEq => ">="
    case Equal => "=="
  }
  
  def printGurobi(x: Objective): String = x match {
    case MinObjective(e) => 
      s"model.setObjective(${printGurobi(e)}, GRB.MINIMIZE)"
    case MaxObjective(e) => 
      s"model.setObjective(${printGurobi(e)}, GRB.MAXIMIZE)"
  }
  
  /**
   * 索引表达式转换
   */
  def printGurobi(y: Index): String = y match {
    case Index(x: String, d: Dim) => x
  }
  
  def printGurobiSum(y: Index): String = y match {
    case Index(x: String, d: Dim) => x + printGurobiDim(d)
  }
  
  def printGurobiDim(x: Dim): String = x match {
    case Dim(n: Int, name: String) => s" in $name"
  }
  
  /**
   * 约束转换
   */
  def printGurobi(x: Equation): String = x match {
    case Equation(left: Exp, op: Cop, right: Exp) =>
      s"""model.addConstr(${printGurobi(left)} ${printGurobi(op)} ${printGurobi(right)}, name="${getConstraintName(left)}")"""
  }
  
  /**
   * 表达式转换
   */
  def printGurobi(x: Exp): String = x match {
    case Const(n) =>
      if (n % 1 == 0) n.toInt.toString else n.toString
    
    case VecElem(v, indices) =>
      val base = printGurobi(v)
      val idxStr = indices.map(i => printGurobi(i.asInstanceOf[Index])).mkString(",")
      s"$base[$idxStr]"
    
    case Sum(idx, e) => 
      s"gp.quicksum(${printGurobi(e)} for ${printGurobiSum(idx)})"
    
    case AExp(e1, op, e2) => 
      s"(${printGurobi(e1)} ${printGurobi(op)} ${printGurobi(e2)})"
    
    case PowExp(e, n) => 
      s"(${printGurobi(e)} ** $n)"
    
    case InputVar(y) => y
    
    case IntegerVariable(y) => y
    
    case ContinuousVariable(y) => y
    
    case BinaryVar(y) => y
    
    case _ => "expr"
  }
  
  /**
   * 获取约束名称
   */
  private def getConstraintName(exp: Exp): String = exp match {
    case InputVar(name) => name
    case IntegerVariable(name) => name
    case ContinuousVariable(name) => name
    case BinaryVar(name) => name
    case VecElem(v, indices) => printGurobi(v)
    case _ => "c"
  }
  
  /**
   * 变量声明生成
   */
  def generateVariableDecl(x: Exp): List[String] = x match {
    case IntegerVariable(name) =>
      List(s"${name} = model.addVar(vtype=GRB.INTEGER, name='$name')")
    
    case ContinuousVariable(name) =>
      List(s"${name} = model.addVar(vtype=GRB.CONTINUOUS, name='$name')")
    
    case BinaryVar(name) =>
      List(s"${name} = model.addVar(vtype=GRB.BINARY, name='$name')")
    
    case VecElem(v, indices) =>
      val baseName = printGurobi(v)
      val idxSet = indices.map(i => i match {
        case Index(name, dim) => (name, dim)
      })
      val setNames = idxSet.map(_._2 match {
        case Dim(_, name) => name
      })
      List(
        s"# Indexed variable: $baseName",
        s"${baseName} = model.addVars(${setNames.mkString(",")}, vtype=GRB.CONTINUOUS)"
      )
    
    case _ => List()
  }
  
  /**
   * 完整公式转换
   */
  def printGurobi(x: Formula): String = {
    val sb = new StringBuilder
    
    sb ++= "#!/usr/bin/env python3\n"
    sb ++= "# -*- coding: utf-8 -*-\n"
    sb ++= "# Generated by ORMDSL AST2Gurobi\n\n"
    sb ++= "import gurobipy as gp\n"
    sb ++= "from gurobipy import GRB\n\n"
    
    sb ++= "def create_model():\n"
    sb ++= "    model = gp.Model('ormdsl_model')\n\n"
    
    // 目标函数
    sb ++= "    # Objective\n"
    x.objective match {
      case MinObjective(e) =>
        sb ++= s"    model.setObjective(${printGurobi(e)}, GRB.MINIMIZE)\n"
      case MaxObjective(e) =>
        sb ++= s"    model.setObjective(${printGurobi(e)}, GRB.MAXIMIZE)\n"
    }
    
    // 约束
    sb ++= "\n    # Constraints\n"
    x.equations.foreach { eq =>
      sb ++= s"    ${printGurobi(eq.asInstanceOf[Equation])}\n"
    }
    
    sb ++= "\n    model.optimize()\n"
    sb ++= "    return model\n\n"
    sb ++= "if __name__ == '__main__':\n"
    sb ++= "    create_model()\n"
    
    sb.toString
  }
  
  /**
   * 批量约束生成
   */
  def generateConstraints(equations: List[Equation]): List[String] = {
    equations.map { eq =>
      s"model.addConstr(${printGurobi(eq.left)} ${printGurobi(eq.op)} ${printGurobi(eq.right)})"
    }
  }
  
  /**
   * 生成集合索引循环
   */
  def generateSetLoop(setName: String, indices: List[String], body: String): String = {
    val idxVars = indices.mkString(", ")
    s"for $idxVars in $setName:\n        $body"
  }
}
