package ormgurobi

/**
 * 代码生成器基类
 * 定义通用的代码生成接口和工具函数
 */

abstract class CodeGenerator {
  
  // 缩进级别
  protected var indentLevel: Int = 0
  protected val indentString: String = "    "
  
  // 缩进控制
  protected def indent(): String = indentString * indentLevel
  protected def indent(block: => String): String = {
    indentLevel += 1
    val result = block
    indentLevel -= 1
    result
  }
  
  // 关键字转义
  protected val pythonKeywords = Set(
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
    "try", "while", "with", "yield"
  )
  
  protected def sanitizeName(name: String): String = {
    val sanitized = name.replaceAll("[^a-zA-Z0-9_]", "_")
    if (pythonKeywords.contains(sanitized)) s"${sanitized}_" else sanitized
  }
  
  // 生成文件头
  protected def generateHeader(): String = {
    s"""#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by ORMDSL-Gurobi Code Generator
#
# Requirements:
#   - Gurobi Optimizer (https://www.gurobi.com/downloads/)
#   - Python API: pip install gurobipy
#
"""
  }
  
  // 生成导入语句
  protected def generateImports(): String = {
    """import gurobipy as gp
from gurobipy import GRB

"""
  }
  
  // 生成模型初始化
  protected def generateModelInit(name: String): String = {
    s"""def create_model():
    \"\"\"Create and return a Gurobi model.\"\"\"
    model = gp.Model('$name')
    
    # Model parameters (optional)
    # model.Params.TimeLimit = 3600  # 1 hour time limit
    # model.Params.MIPGap = 0.01      # 1% optimality gap
    
"""
  }
  
  // 生成求解代码
  protected def generateSolve(): String = {
    """
    # Optimize
    model.optimize()
    
    # Check solution status
    if model.status == GRB.OPTIMAL:
        print(f"Optimal objective value: {model.objVal:.4f}")
        print(f"Solution time: {model.runtime:.2f} seconds")
        print("\\nDecision variables:")
        for v in model.getVars():
            if v.x != 0:  # Only show non-zero variables
                print(f"  {v.varName}: {v.x}")
    elif model.status == GRB.TIME_LIMIT:
        print(f"Time limit reached. Best bound: {model.objBound:.4f}")
    else:
        print(f"Optimization status: {model.status}")
    
    return model

"""
  }
  
  // 生成主函数
  protected def generateMain(): String = {
    """if __name__ == '__main__':
    model = create_model()
    
"""
  }
}

// 辅助工具对象
object GurobiUtils {
  
  // Big-M 常量
  val BIG_M = 1e6
  val NEG_BIG_M = -1e6
  
  // 常用集合范围
  def range(min: Int, max: Int): String = s"range($min, $max + 1)"
  
  // LinExpr 构造
  def linExpr(terms: (String, Double)*): String = {
    val quicksum = terms.map { case (v, c) => s"$c * $v" }.mkString(" + ")
    s"gp.LinExpr([${terms.map(_._2).mkString(",")}], [${terms.map(t => s"${t._1}").mkString(",")}])"
  }
  
  // QuadExpr 构造
  def quadExpr(quadTerms: (String, String, Double)*, linTerms: (String, Double)*): String = {
    val qExpr = if (quadTerms.nonEmpty) {
      val qStr = quadTerms.map { case (v1, v2, c) => s"$c * $v1 * $v2" }.mkString(" + ")
      s"($qStr)"
    } else ""
    val lExpr = if (linTerms.nonEmpty) {
      val lStr = linTerms.map { case (v, c) => s"$c * $v" }.mkString(" + ")
      s"+ ($lStr)"
    } else ""
    s"gp.QuadExpr($qExpr$lExpr)"
  }
  
  // 生成蕴含约束 (x=1 => y=1) 转换为 Big-M 形式
  def implies(x: String, y: String): String = {
    s"y <= x  # $x == 1 implies $y == 1 (Big-M formulation)"
  }
  
  // 生成析取约束 (x=1 OR y=1)
  def disjunction(x: String, y: String, name: String): String = {
    s"""# Disjunction: $x + $y >= 1
model.addConstr($x + $y >= 1, name='$name')"""
  }
  
  // 生成互斥约束 (最多一个为1)
  def atMostOne(vars: String*): String = {
    val sum = vars.mkString(" + ")
    s"model.addConstr($sum <= 1)  # At most one of [${vars.mkString(", ")}]"
  }
  
  // 生成恰好一个约束
  def exactlyOne(vars: String*): String = {
    val sum = vars.mkString(" + ")
    s"model.addConstr($sum == 1)  # Exactly one of [${vars.mkString(", ")}]"
  }
}
