package ormgurobi

/**
 * Gurobi求解器模型包装类
 * 提供高级API来构建优化模型并生成Python代码
 */

// 变量类型枚举
sealed trait VarType
case object Continuous extends VarType { override def toString = "GRB.CONTINUOUS" }
case object Integer extends VarType { override def toString = "GRB.INTEGER" }
case object Binary extends VarType { override def toString = "GRB.BINARY" }

// 目标函数方向
sealed trait ObjectiveSense
case object Minimize extends ObjectiveSense { override def toString = "GRB.MINIMIZE" }
case object Maximize extends ObjectiveSense { override def toString = "GRB.MAXIMIZE" }

// Gurobi模型类
class GurobiModel(val name: String) {
  private val variables = scala.collection.mutable.ListBuffer[String]()
  private val constraints = scala.collection.mutable.ListBuffer[String]()
  private val expressions = scala.collection.mutable.ListBuffer[String]()
  private var objectiveExpr: Option[String] = None
  private var objectiveSense: ObjectiveSense = Minimize
  
  // 变量名称映射 (避免与Python关键字冲突)
  private val varNameMap = scala.collection.mutable.Map[String, String]()
  
  // 添加连续变量
  def addVar(name: String, lb: Double = 0.0, ub: Double = Double.PositiveInfinity, 
             vtype: VarType = Continuous, comment: String = ""): this.type = {
    val safeName = sanitizeName(name)
    variables += s"# Variable: $name ${if(comment.nonEmpty) s"($comment)" else ""}"
    variables += s"$safeName = model.addVar(lb=$lb, ub=$ub, vtype=$vtype, name='$safeName')"
    varNameMap(name) = safeName
    this
  }
  
  // 添加索引变量 (用于集合操作)
  def addIndexedVar(baseName: String, indexSet: String, 
                    lb: Double = 0.0, ub: Double = Double.PositiveInfinity,
                    vtype: VarType = Continuous): this.type = {
    val safeName = sanitizeName(baseName)
    variables += s"# Indexed variable: ${baseName}[{indexSet}]"
    variables += s"${safeName} = {}"
    variables += s"for ${indexSet}_idx in $indexSet:"
    variables += s"    ${safeName}[${indexSet}_idx] = model.addVar(lb=$lb, ub=$ub, vtype=$vtype, name='${safeName}[{%${indexSet}_idx}]')"
    varNameMap(baseName) = safeName
    this
  }
  
  // 添加约束
  def addConstraint(name: String, lhs: String, sense: String, rhs: String): this.type = {
    val safeName = sanitizeName(name)
    val pythonSense = sense match {
      case "<=" | "<" => "GRB.LESS_EQUAL"
      case ">=" | ">" => "GRB.GREATER_EQUAL"
      case "=" | "==" => "GRB.EQUAL"
      case _ => sense
    }
    constraints += s"# Constraint: $name"
    constraints += s"model.addConstr($lhs $sense $rhs, name='$safeName')"
    this
  }
  
  // 添加范围约束 lb <= expr <= ub
  def addRangeConstraint(name: String, expr: String, lb: Double, ub: Double): this.type = {
    val safeName = sanitizeName(name)
    constraints += s"# Range constraint: $name ($lb <= expr <= $ub)"
    constraints += s"model.addRange($expr, lb=$lb, ub=$ub, name='$safeName')"
    this
  }
  
  // 设置目标函数
  def setObjective(expression: String, sense: ObjectiveSense = Minimize): this.type = {
    objectiveExpr = Some(expression)
    objectiveSense = sense
    this
  }
  
  // 设置多目标
  def setMultiObjective(priorities: (String, Double, ObjectiveSense)*): this.type = {
    // Gurobi 9.0+ 支持多目标
    objectiveExpr = Some(priorities.head._1)
    objectiveSense = priorities.head._3
    priorities.drop(1).zipWithIndex.foreach { case ((expr, priority, sense), idx) =>
      expressions += s"# Multi-objective ${idx + 2}: priority=$priority"
      expressions += s"model.setObjectiveN($expr, priority=${priority.toInt}, weight=0, name='obj_${idx + 2}')"
    }
    this
  }
  
  // 添加通用表达式
  def addExpression(code: String): this.type = {
    expressions += code
    this
  }
  
  // 清理变量名 (避免Python关键字)
  private def sanitizeName(name: String): String = {
    val reserved = Set("if", "else", "for", "while", "def", "class", "import", 
                       "export", "and", "or", "not", "in", "is", "True", "False", "None")
    val safe = name.replace(" ", "_").replace("-", "_")
    if (reserved.contains(safe)) s"${safe}_" else safe
  }
  
  // 获取映射后的变量名
  def getVarName(name: String): String = varNameMap.getOrElse(name, sanitizeName(name))
  
  // 生成完整的Python代码
  def generatePythonCode(): String = {
    val sb = new StringBuilder
    
    sb ++= "#!/usr/bin/env python3\n"
    sb ++= "# -*- coding: utf-8 -*-\n"
    sb ++= s"# Generated by ORMDSL-Gurobi for model: $name\n"
    sb ++= "#\n"
    sb ++= "# Usage:\n"
    sb ++= "#   1. Install Gurobi: pip install gurobipy\n"
    sb ++= "#   2. Set GUROBI_HOME environment variable\n"
    sb ++= "#   3. Run: python generated_model.py\n"
    sb ++= "\n"
    
    sb ++= "import gurobipy as gp\n"
    sb ++= "from gurobipy import GRB\n"
    sb ++= "\n"
    
    sb ++= "def solve():\n"
    sb ++= s"    model = gp.Model('$name')\n"
    sb ++= "\n"
    
    // 变量声明
    if (variables.nonEmpty) {
      sb ++= "    # ===== Decision Variables =====\n"
      variables.foreach { v => sb ++= s"    $v\n" }
      sb ++= "\n"
    }
    
    // 表达式
    if (expressions.nonEmpty) {
      sb ++= "    # ===== Expressions =====\n"
      expressions.foreach { e => sb ++= s"    $e\n" }
      sb ++= "\n"
    }
    
    // 目标函数
    if (objectiveExpr.isDefined) {
      sb ++= "    # ===== Objective Function =====\n"
      sb ++= s"    model.setObjective($objectiveExpr, ${objectiveSense.toString})\n"
      sb ++= "\n"
    }
    
    // 约束
    if (constraints.nonEmpty) {
      sb ++= "    # ===== Constraints =====\n"
      constraints.foreach { c => sb ++= s"    $c\n" }
      sb ++= "\n"
    }
    
    sb ++= "    # ===== Solve =====\n"
    sb ++= "    model.optimize()\n"
    sb ++= "\n"
    sb ++= "    # ===== Output Results =====\n"
    sb ++= "    if model.status == GRB.OPTIMAL:\n"
    sb ++= "        print(f'Optimal objective value: {model.objVal}')\n"
    sb ++= "        print(f'Optimal solution found in {model.runtime:.2f} seconds')\n"
    sb ++= "        for v in model.getVars():\n"
    sb ++= "            if v.x != 0:  # Only print non-zero variables\n"
    sb ++= "                print(f'{v.varName} = {v.x}')\n"
    sb ++= "    else:\n"
    sb ++= "        print(f'Optimization ended with status: {model.status}')\n"
    sb ++= "    \n"
    sb ++= "    return model\n"
    sb ++= "\n"
    sb ++= "if __name__ == '__main__':\n"
    sb ++= "    solve()\n"
    
    sb.toString
  }
  
  // 直接求解 (需要Gurobi安装)
  def solve(): Option[GurobiResult] = {
    val code = generatePythonCode()
    val tempFile = java.io.File.createTempFile("gurobi_model_", ".py")
    val writer = new java.io.PrintWriter(tempFile)
    writer.write(code)
    writer.close()
    
    try {
      val process = Runtime.getRuntime.exec(s"python ${tempFile.getAbsolutePath}")
      val reader = new java.io.BufferedReader(new java.io.InputStreamReader(process.getInputStream))
      val errorReader = new java.io.BufferedReader(new java.io.InputStreamReader(process.getErrorStream))
      
      val output = Iterator.continually(reader.readLine()).takeWhile(_ != null).mkString("\n")
      val errors = Iterator.continually(errorReader.readLine()).takeWhile(_ != null).mkString("\n")
      
      val exitCode = process.waitFor()
      reader.close()
      errorReader.close()
      
      if (exitCode == 0) Some(GurobiResult(success = true, output = output))
      else Some(GurobiResult(success = false, output = errors))
    } catch {
      case e: Exception => Some(GurobiResult(success = false, output = e.getMessage))
    } finally {
      tempFile.delete()
    }
  }
}

// 求解结果
case class GurobiResult(success: Boolean, output: String)

// 伴生对象 - 工厂方法
object GurobiModel {
  def apply(name: String): GurobiModel = new GurobiModel(name)
  
  def createKnapsack(): GurobiModel = {
    val model = GurobiModel("knapsack")
    model.addExpression("# Example: 0-1 Knapsack Problem")
    model.addExpression("# maximize sum(profit[i] * x[i])")
    model.addExpression("# subject to: sum(weight[i] * x[i]) <= capacity")
    model.addExpression("# x[i] in {0, 1}")
    model
  }
  
  def createFacilityLocation(): GurobiModel = {
    val model = GurobiModel("facility_location")
    model.addExpression("# Example: P-Median Problem")
    model
  }
}
